# Generated by Django 4.1.7 on 2023-09-09 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('wheelers', models.CharField(choices=[('two', 'Two Wheeler'), ('four', 'Four-Wheeler')], max_length=10)),
                ('submission_date', models.DateTimeField()),
                ('servicing', models.ManyToManyField(blank=True, choices=[(1, 'Washing'), (2, 'Waterless cleaning'), (3, 'Engine oil'), (4, 'Leakage'), (5, 'Maintenance'), (6, 'Full Servicing')], to='vehicle.appointment')),
            ],
        ),
    ]
